const quotes = [
  {
    quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: "Winston Churchill",
  },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { quote: "Your limitation—it’s only your imagination.", author: "KBM Tech" },
  { quote: "Push yourself, because no one else is going to do it for you.", author: "KBM Tech" },
  { quote: "Great things never come from comfort zones.", author: "KBM Tech" },
  { quote: "Dream it. Wish it. Do it.", author: "KBM Tech" },
  { quote: "Success doesn’t just find you. You have to go out and get it.", author: "KBM Tech" },
  { quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "KBM Tech" },
  { quote: "Dream bigger. Do bigger.", author: "KBM Tech" },
  { quote: "Don’t stop when you’re tired. Stop when you’re done.", author: "KBM Tech" },
  { quote: "Wake up with determination. Go to bed with satisfaction.", author: "KBM Tech" },
  { quote: "Do something today that your future self will thank you for.", author: "KBM Tech" },
  { quote: "Little things make big days.", author: "KBM Tech" },
  { quote: "It’s going to be hard, but hard does not mean impossible.", author: "KBM Tech" },
  { quote: "Don’t wait for opportunity. Create it.", author: "KBM Tech" },
  { quote: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "KBM Tech" },
  { quote: "The key to success is to focus on goals, not obstacles.", author: "KBM Tech" },
  { quote: "Dreams don’t work unless you do.", author: "KBM Tech" },
  { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { quote: "You are capable of amazing things.", author: "KBM Tech" },
  { quote: "Failure is the opportunity to begin again more intelligently.", author: "Henry Ford" },
  { quote: "Hustle in silence and let your success make the noise.", author: "KBM Tech" },
  { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { quote: "Opportunities don’t happen, you create them.", author: "Chris Grosser" },
  { quote: "Work hard in silence, let success be your noise.", author: "Frank Ocean" },
  {
    quote: "Go confidently in the direction of your dreams. Live the life you have imagined.",
    author: "Henry David Thoreau",
  },
  { quote: "If you’re going through hell, keep going.", author: "Winston Churchill" },
  { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  {
    quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    author: "Zig Ziglar",
  },
  { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { quote: "Difficulties in life are intended to make us better, not bitter.", author: "KBM Tech" },
  { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { quote: "Do what makes your soul shine.", author: "KBM Tech" },
  { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { quote: "Take risks: if you win, you will be happy; if you lose, you will be wise.", author: "KBM Tech" },
  { quote: "You are stronger than you think.", author: "KBM Tech" },
  { quote: "Every day may not be good, but there’s something good in every day.", author: "KBM Tech" },
  { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { quote: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { quote: "You must do the thing you think you cannot do.", author: "Eleanor Roosevelt" },
  { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
  { quote: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain" },
  { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { quote: "Only I can change my life. No one can do it for me.", author: "Carol Burnett" },
  { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
  {
    quote: "Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.",
    author: "Vivian Greene",
  },
  { quote: "Be fearless in the pursuit of what sets your soul on fire.", author: "KBM Tech" },
  { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
];

export default quotes;
